---
layout: post
title: Translating Your Bash Configuration to Eshell
date: August 3rd, 2017
author: Skye Freeman
description: One of the mental barriers I had in making the switch over from iTerm2
  + Bash to the Emacs Eshell was translating my .bash_profile into Emacs Lisp.
url_slug: converting-your-bash-config-to-eshell
